name: Building Docker image

on: 
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
    build: 
        runs-on: self-hosted
        steps:
            - name: Checkout code 
              uses: actions/checkout@v4
            -  name: Login to Docker Hub
               uses: docker/login-action@v3
               with:
                 username: ${{ secrets.DOCKERHUB_USERNAME }}
                 password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build Docker image
              run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/chess:${{ github.sha }} .
            # - name: Run Trivy vulnerability scanner
            #   uses: aquasecurity/trivy-action@0.28.0
            #   with:
            #     image-ref: ${{ secrets.DOCKERHUB_USERNAME }}/chess:${{ github.sha }}
            #     format: 'table'
            #     exit-code: '1'
            #     ignore-unfixed: true
            #     vuln-type: 'os,library'
            #     severity: 'CRITICAL,HIGH'
            - name: publish Docker Image
              if: success()
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/chess:${{ github.sha }}
            - name: check kubectl
              run: kubectl get nodes
                    
                    