name: Building Docker image

on: 
    push:
        branches:
            - main

jobs:
    build: 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code 
              uses: actions/checkout@v4
            -  name: Set up Docker Buildx
               uses: docker/setup-buildx-action@v3
            -  name: Login to Docker Hub
               uses: docker/login-action@v3
               with:
                 username: ${{ secrets.DOCKERHUB_USERNAME }}
                 password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build docker image
              uses: docker/build-push-action@v6
              with:
                push: false
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/chess:${{ github.sha }}
            - name: Run Trivy vulnerability scanner
              uses: aquasec/trivy-action@master
              with:
                image: ${{ secrets.DOCKERHUB_USERNAME }}/chess:${{ github.sha }}
            - name: publish Docker Image
              if: success()
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{ secrets.DOCKERHUB_USERNAME }}/chess:${{ github.sha }}
                    
                    